let
    Source = Csv.Document(File.Contents("D:\Internship\DataForge_EDA_Sprint_2026_Vijayalaxmi_Sundalam\01_data\raw\dataset_raw.csv"),[Delimiter=",", Columns=18, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Order ID", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Order ID.1", "Order ID.2", "Order ID.3"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Order ID.1", type text}, {"Order ID.2", Int64.Type}, {"Order ID.3", Int64.Type}}),
    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"Row ID", "Order ID.1", "Order ID.2", "Order ID.3", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country", "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales"}),
    #"Added Conditional Column" = Table.AddColumn(#"Removed Errors", "Profitability", each if [Sales] > 0 then "Profitable" else "Loss"),
    #"Inserted Year" = Table.AddColumn(#"Added Conditional Column", "Year", each Date.Year([Order Date]), Int64.Type)
in
    #"Inserted Year"